name: CI-CD-Pipeline-to-AWS-ElasticBeanStalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: "vitali-lylo-bucket-cicd"
  EB_APPLICATION_NAME: "MyFlask2"
  EB_ENVIRONMENT_NAME: "MyFlask2-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-west-2"

on:
  push:
    branches:
      - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git Clone Our Repo
      uses: actions/checkout@v1

    - name: Create Zip Deployment Package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
    
